### ISSUE TITLE
Nested prefabs

### ISSUE THREAD

**Issue by 13Flo** [Ayfel/PrefabLightmapping#1]
That's great. Thanks for sharing.

Is this script compatible with 2018.3 and nested prefabs?

**Comment by 13Flo** [comment]
Just tested and it works like a charm with 2018.3 + LWRP

To be honest, I was expected this to take a lot more time to figure out. I am so happy I found your repo. 
THANK YOU. Really, I mean it!

**Comment by Ayfel** [comment]
Great to know! You are welcome : )
