### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by Dawid93** [Ayfel/PrefabLightmapping#12]
Hello, I can't find anything about license in this repository so could you tell me can I use this script in my personal or commercial projects? 

If this is not a problem for you I suggest to add a clear license like CC0 to Readme.md for future users.

**Comment by Ayfel** [comment]
Yes go ahead and use it freely. I can add a simple license in the readme, good idea 😊

**Comment by Dawid93** [comment]
Thanks for the answer. ;)
