### ISSUE TITLE
Compilation Error on new project

### ISSUE THREAD

**Issue by farwest912** [Ayfel/PrefabLightmapping#13]
Hi Ayfel, there are these two errors thrown in Unity Console, I will appreciate if you can offer a fix, thanks. Because I am a designer not good at coding, I couldn't fix myself. 

```
Assets/Scripts/PrefabLightmapData.cs(72,107): error CS1525: Unexpected symbol `,', expecting `('
Assets/Scripts/PrefabLightmapData.cs(73,105): error CS1525: Unexpected symbol `,', expecting `('
```

**Comment by Ayfel** [comment]
Mmm, I just imported the script into a new project and it compiles fine. What version of Unity are you using? Can you delete the script and download it again just in case?

**Comment by farwest912** [comment]
I use Unity 2017.4.40 now. Unfortunately result is same, it throws same errors. :/

**Comment by Ayfel** [comment]
Is this a brand new project?

**Comment by farwest912** [comment]
It is work project (60 GB) without errors. 

I tried the script in a new project and it throws same error unfortunately.

**Comment by Ayfel** [comment]
Ok I figured it out, its because of an older version of .Net, give me a min to get a more general version that's backwards compatible

**Comment by farwest912** [comment]
Thanks, I will be checking for updates.

**Comment by Ayfel** [comment]
It's updated and tested on 2017.4.40 : )

**Comment by farwest912** [comment]
Thanks for the "2017 compatibility edition", I appreciate it very much.
