### ISSUE TITLE
No feedback

### ISSUE THREAD

**Issue by somehalaldev79** [Ayfel/PrefabLightmapping#14]
When I clicked on Bake prefab from assets the editor just froze there was no visual feedback as to if the lights were being baked...were they?
Usually, it takes 15-20 mins to bake the same prefab, so should I just wait for 20 mins and hopefully it magically bakes and unfreezes? Or is there a problem?

(I know it's technically not an issue that I should open up but there was no other way to ask the question 😉)

**Comment by Ayfel** [comment]
You are right there is no prompt currently showing the progress but I can look into adding one, I dont know if Unity reports back some but it should.

There is a small visual feedback at least in Windows when I bake which is the Unity icon at the bottom which shows a green fill up (not a fix, just a trick :p).

Thanks for the comment anyway, I will look into it when I have some time.

**Comment by somehalaldev79** [comment]
The owner said he will look into but for the time being, the unity icon on the taskbar fills up which can be used to tell if it is working or not.
