### ISSUE TITLE
Lightmap not used after applying to prefab

### ISSUE THREAD

**Issue by BGDaan** [Ayfel/PrefabLightmapping#15]
I'm having some trouble using this. After baking my lights when I do the _Assets > Bake Prefab Lightmaps_ everything seems to be going well. The script on the prefab is being populated. 

But then when I look into the prefab, everything is unlit again. It's not being applied. And going back to the scene everything is gone as well. Do you have any insights on this issue?

I'm working on Unity 2019.2.9f1.

**Comment by Telroshan** [comment]
I guess it's only applied on Awake and scene loaded, at runtime
@Ayfel I wonder if adding a [ExecuteAlways](https://docs.unity3d.com/ScriptReference/ExecuteAlways.html) tag to make it happen in Editor & Prefab Mode as well would have any drawback ?

**Comment by BGDaan** [comment]
You are right. It works. Thank you for clearing that up :)

**Comment by Ayfel** [comment]
Yes you are right about that, I dont think there is any drawback, so I might add that in the next commit, thanks : )
