### ISSUE TITLE
Not working on the build

### ISSUE THREAD

**Issue by elhongo** [Ayfel/PrefabLightmapping#2]
Hey Ayfel, 

Thanks for this amazing tool. In the editor this works great but on an actual build, the light data does not seem to apply correctly. 

I've tested on Android and Windows without any luck. Also tried putting the light data inside Resources to make sure that the light data was bundled in the build. 

Running on Unity 2018.2.20f1. 

Any ideas?

Thanks.

**Comment by Ayfel** [comment]
Any errors in the log file? I will take a look on my end and let you know what I find

**Comment by elhongo** [comment]
Unfortunately no errors on the log file. Been trying out different Player Settings without any luck. Let me know if you have any insights. 

Thanks!

**Comment by Ayfel** [comment]
Check your Graphic settings in Project Settings for shader stripping see if maybe lightmap shaders are being stripped 

![image](https://user-images.githubusercontent.com/13970424/60190570-7dd05680-97f8-11e9-991f-f54b816a577f.png)

**Comment by elhongo** [comment]
Awesome. Yes, this was the issue. Shader Stripping Lightmap Modes set to Automatic causes the issue. If you set this to Custom everything works perfectly. 

Thanks for the help! Super appreciate it. 

Might be a good idea to add this into the Readme. 

:-)

**Comment by Ayfel** [comment]
Great! yes I might add that into the readme, thanks.
