### ISSUE TITLE
Having realtime shadows on the baked prefabs

### ISSUE THREAD

**Issue by FedericoCara** [Ayfel/PrefabLightmapping#20]
Hi, I made the bake on some prefabs, and now when I try them in a new scene they are affected by the directional light as if they have not been baked. I tried changing the layer of the meshes inside the prefabs so that I set the directional light in the scene to that the culling mask don't affect them. It solves the "double" lighting issue, but now shadows are not casted onto them (which makes sense...) I suppose there must be a way of making the prefabs behave as already baked.

**Comment by Ayfel** [comment]
I recommend playing with mixed lighting https://docs.unity3d.com/2018.3/Documentation/Manual/LightMode-Mixed.html to get the effect you want. You can also remove the the directional light from the scene and only have lights inside the prefabs. Many ways to achieve what you might want to show.
