### ISSUE TITLE
Does not work with Probuilder

### ISSUE THREAD

**Issue by christianhanne** [Ayfel/PrefabLightmapping#21]
First of all, thanks for this awesome script. It works like a charm with most models. 

Unfortunately there seems to be a problem with meshes created with Probuilder. When creating a model with probuilder inside Unity and using it as a prefab, the lightmaps seem to be misplaced. Also when using a complex prefab with Probuilder elements and normal elements, all normal elements (thanks to your script) have the correct lighting. All Probuilder elements look messed up. Therefore I think this is a problem of Probuilder.

I will recreate the affected elements outside of Unity now. Just leaving this as a comment so others won't have to search forever.

**Comment by Ayfel** [comment]
Oh that's interesting I wonder if Probuilder is doing some sort of batching and messing up the UVs, are they "static"? I haven't played with probuilder but if I do I will keep it in mind

**Comment by christianhanne** [comment]
Sorry, for my late reply. I tried both, static and non-static. Neither one worked for me. I think this is because Probuilder adds the meshes on the fly through the added Probuilder Script. The Prefabs also are always displayed as overwritten when used in a scene. So I think this is just a problem with the inner workings of Probuilder.
