### ISSUE TITLE
Baked Objects Get Darker After Reloading Scene

### ISSUE THREAD

**Issue by ImanTanumihardja** [Ayfel/PrefabLightmapping#22]
Hi, thank you for this script it has really helped optimize performance in my mobile game. 

However, I am having issues with game objects appearing darker after the scene is reloaded. Do you know if this issue is caused by the script or maybe something else?

In the video, the cars become darker after I reload the scene (Ignore the dark buildings):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34433210/93522989-2cbdee00-f8e7-11ea-97f7-2f3feb42cc7f.gif)

Before Reload:
![LightmapIssue](https://user-images.githubusercontent.com/34433210/93523090-5d058c80-f8e7-11ea-8fee-e0e8b5b714ec.JPG)

After Reload:
![LightmapIssue2](https://user-images.githubusercontent.com/34433210/93523094-5ecf5000-f8e7-11ea-80c2-9867ec7ee4bc.JPG)

Any help would be greatly apperciated.

**Comment by Ayfel** [comment]
mmm I would make sure you are calling the Init() function on the prefablightmapping script, maybe the way the scene is reloading it is not calling that. You can manually call it from whatever script you have in the car on Start or similar. Let me know if manually calling that fixes it (you might have to make the Init() public)

**Comment by ImanTanumihardja** [comment]
Thanks for the quick reply. Yea that was the issue

**Comment by Ayfel** [comment]
Great : )
