### ISSUE TITLE
Doesn't appear to save lightmaps when pressing store prefab lightmaps

### ISSUE THREAD

**Issue by nneroutsos** [Ayfel/PrefabLightmapping#23]
I tried using that after baking my scene, and then going to assets like the instructions and pressing the bake prefab lightmaps, to no avail since the saved prefab doesnt got the lightmap saved nor does it get applied when i press play on a new scene.

**Comment by Ayfel** [comment]
So just to make sure, some basic questions, is the script on the parent object in the prefab? Is it marked static for the bake?

**Comment by nneroutsos** [comment]
Okay i apologize i forgot to mark for static to bake, pardon im closing this issue as it is not needing further help, thanks for taking the time to help me.
