### ISSUE TITLE
It shows black on Android devices.

### ISSUE THREAD

**Issue by kishorpd** [Ayfel/PrefabLightmapping#24]
Works perfect on Windows and was amazed by the ease provided.

My steps for repro: 
I have two independent Android Unity projects. I am exporting from one project and importing in other. Both projects contain the lightmapping script. Works on the Windows device[tested only in Editor with build settings set to Android ] but after making a build for Android it shows black on the Android device, only the skybox is colored, all the baked static items are black.

I have made sure via runtime Hierarchy that the script is loading correctly and that all the parameters are set correctly.
Tested on all three Graphics Api : Opengl3, 2 & Vulkan. Got same results on the Android device.
Using Unity 2019.4.10 (LTS).

Please see  the attached images.

[ Lucky to find this repo after spending almost 6+ hours on this issue. Thank you for the great work! ]

![image](https://user-images.githubusercontent.com/18411802/93776251-011d6980-fc41-11ea-9224-ced0b364bc7a.png)
![WhatsApp Image 2020-09-21 at 7 33 51 PM](https://user-images.githubusercontent.com/18411802/93776660-68d3b480-fc41-11ea-9731-ff7e0e822acf.jpeg)

**Comment by Ayfel** [comment]
Did you check the shader stripping? This normally happens in builds, check the readme of the repository for a picture of the menu item to unlock.

**Comment by kishorpd** [comment]
Yes, I did the Strip Unused setting right before starting in both the projects.

![image](https://user-images.githubusercontent.com/18411802/93781761-58bed380-fc47-11ea-88f8-a022057c8100.png)

**Comment by Ayfel** [comment]
Try with Custom instead of automatic for "Lightmap Modes" since mobile might be stripping it regardless, you will get a dropdown and can select all lightmapping modes

**Comment by kishorpd** [comment]
Thank you so much!! 🤩

Here are the settings I am on, for future reference : 
![image](https://user-images.githubusercontent.com/18411802/93796424-77799600-fc58-11ea-922c-c9d1e3649ade.png)

![image](https://user-images.githubusercontent.com/18411802/93796366-5dd84e80-fc58-11ea-83a0-ef4e3eea48ab.png)

![WhatsApp Image 2020-09-21 at 10 20 07 PM](https://user-images.githubusercontent.com/18411802/93796559-a3951700-fc58-11ea-8d9c-defc4bdfe4dc.jpeg)
