### ISSUE TITLE
Misaligned lightmaps when using BakeAsync()

### ISSUE THREAD

**Issue by brunce** [Ayfel/PrefabLightmapping#27]
My lightmaps are misaligned when using this script for baking. I use Unity 2020.1.12f and have some complicated and unoptimized geometry.

I think the reason is that the script uses` BakeAsync()` without waiting for the bake to complete. Instead it assigns the currently existing lightmaps immediatly. Or nothing if no lightmap existed.

However when starting the bake in Unity and after completion running the script without the `BakeAsync()` call everything is working fine and aligned correctly.

In any case, this script is a tremendous help. Thank you.

**Comment by Ayfel** [comment]
I have returned it to Bake() until I have time to test and implement the async version properly, which I hadnt
