### ISSUE TITLE
Why is baking right, but when I save the prefab and then put it in, the prefab is dimmed

### ISSUE THREAD

**Issue by smallnail21** [Ayfel/PrefabLightmapping#29]
Why is baking right, but when I save the prefab and then put it in, the prefab is dimmed

**Comment by Ayfel** [comment]
Mmm, can you share some screenshots and the setup you are using? (Prefabas hierarchy, lights, etc)

**Comment by smallnail21** [comment]
> 构

I found that the files baked in the scene take away the real-time light map, but the saved preset does not have this option. This should be the reason. But it doesn't matter. I solved the problem by adjusting the light map with PS
