### ISSUE TITLE
Save the info in script to another file

### ISSUE THREAD

**Issue by highwaywarrior0** [Ayfel/PrefabLightmapping#30]
Can you make the attached script on root prefab save info in another file?(something like txt)

This
![image](https://user-images.githubusercontent.com/68394892/101375574-9afbc680-38c0-11eb-950b-35c1ac69194c.png)
We really need this and i can explain why if you want.

**Comment by Ayfel** [comment]
Hi, I don't follow, save what info? And what is the purpose?

**Comment by highwaywarrior0** [comment]
We are modding a game with AssetBundles, but we cant include scripts in AssetBundles. We can compile the script into a .dll and attach it to the prefab again but it wont have lightmap info.

But if you make your script save these lightmap data info into a file, we can attach the script with that info. Do you understand what i mean by info now?

**Comment by Ayfel** [comment]
I see, I don't have much experience referencing things inside Assetbundles and it really falls out of the scope of the project by a fair bit. I assume you have no access to the end game to include this script in an update? that would eliminate any need to do what you mention

**Comment by highwaywarrior0** [comment]
We can include the script in a dll and attach it to objects at runtime, but will the objects keep the information while building AssetBundles? The info in attached script, stuff like which objects use which lightmaps
