### ISSUE TITLE
new feat: add script to Empty Game Object instead of object ? 

### ISSUE THREAD

**Issue by Nico3D1982** [Ayfel/PrefabLightmapping#31]
Hi, 
I would like to know if the features below would be possible: 
Can we imagine to add your script to an Empty Game Object and then specify the concerned baked object and maps? 
In our project we are using asset bundle for 3D object but also to save "settings" and load them depending of the needs. 
Having the same with your script would unlock the ability to have multiple baked maps on the same object.
What do you think or do you have any clue how to manage multiple baked maps ? 
Thanks for your reply and your great sript.

**Comment by Ayfel** [comment]
You can do it easily. Just make a prefab with the script (let's call it prefab A), and bake it in some scene, now this stores some lightmaps. Then go to another scene and make another prefab with the script, prefab B, which has different lightmaps (from different scene and lighting). Now make a prefab C with prefab A and B as children. 

![image](https://user-images.githubusercontent.com/13970424/109213540-57ee1880-7776-11eb-8c45-ee4cd0e9c9aa.png)
