### ISSUE TITLE
Does not appear to work?

### ISSUE THREAD

**Issue by Psydrax** [Ayfel/PrefabLightmapping#32]
Hello all,
I was able to get the script to generate the light maps, but when I load the prefabs in a different scene there is no visual change.
Is there a video somewhere showing the proper workflow?

@Ayfel: I was hoping to email or DM you but I couldn't find how to do that. The company I work for is working on a fairly large project that has an "Infrared" view and we think this might be the tool we need to simulate hot spots on our models. We would love to chat about the tool and possibly some minor consulting work.

**Comment by Ayfel** [comment]
If you can share an email here I can contact you.

**Comment by Psydrax** [comment]
tyler.deyoung@bssim.com
