### ISSUE TITLE
Lightmap broken on android and URP

### ISSUE THREAD

**Issue by patricksommer** [Ayfel/PrefabLightmapping#35]
When running on an Android device the result is not as expected.
When using LightmapPrefabData the results are as below. 
Baked lightmapping on static objects without LightmapPrefabData works as expected.

Editor in Play mode
![image](https://user-images.githubusercontent.com/47341906/115560281-6e9a8280-a282-11eb-8c44-09699b323634.png)

Running on Android device
![image](https://user-images.githubusercontent.com/47341906/115560362-83771600-a282-11eb-8b8f-5e7b02d784b2.png)

**Comment by patricksommer** [comment]
there is the following warning, may be applicable:

The renderer GW_Corner_Out_0.012 is a part of a static batch. Setting the lightmap scale and offset will not affect the rendering. The scale and offset is already burnt into the lightmapping UVs in the static batch.
UnityEngine.Renderer:set_lightmapScaleOffset (UnityEngine.Vector4)
PrefabLightmapData:ApplyRendererInfo (PrefabLightmapData/RendererInfo[],int[],PrefabLightmapData/LightInfo[]) (at Assets/Scripts/PrefabLightmapData.cs:134)
PrefabLightmapData:Init () (at Assets/Scripts/PrefabLightmapData.cs:104)
PrefabLightmapData:OnSceneLoaded (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode) (at Assets/Scripts/PrefabLightmapData.cs:118)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode)

**Comment by Ayfel** [comment]
There is a know issue with URP that you can see here #28 , including those in your build/scene should solve it. But the information is good as I haven't seen any messages. I will try to reproduce it, or if you can make a repo project I could check.

**Comment by Ayfel** [comment]
I have just performed tests with 2020.3.5f1 and URP as well as HDRP and built to Android, no issues for me so this might be something else entirely. Let me know if you have any more information
