### ISSUE TITLE
Double lighting

### ISSUE THREAD

**Issue by rakkar1974** [Ayfel/PrefabLightmapping#4]
If I have a static room with a static torch and use "Bake Prefab Lightmaps" this results in double lighting. First, the walls of the room display the baked lighting, indirect in subtractive and baked indirect mode, and both direct and indirect in shadowmask mode. Second, the torch casts light in the scene yet again, because Unity does not recognize this was a baked light and should not be rerendered. During the baking process Unity will save which lights were baked and which were not, so as to avoid this issue. This project doesn't do that. As a result, the project is not useful for prefabs that themselves include lights.

**Comment by Ayfel** [comment]
Can't you turn the light off in your prefab after baking?

**Comment by rakkar1974** [comment]
It's not the same. Mixed lights for example bake indirect light but not
direct light. You also would not have shadows you should have. It also
means post-processing, Aura light, and other effects based on lights
wouldn't work.

**Comment by Ayfel** [comment]
Yes I understand that, I might add that feature at some point, thanks for pointing that out. I had never encountered the issue before but it is obvious once you mention those cases.

**Comment by Ayfel** [comment]
@rakkar1974 I just commited a change adding support for that, you shouldn't get anymore double lighting and I have checked things work well also in mixed modes. It is saving baked lightmaps in the prefabs, applying them at runtime and applying the proper light properties, like their mode and their type (at runtime as well).
