### ISSUE TITLE
Inconsistent application of lightmaps on prefabs instantiated by script

### ISSUE THREAD

**Issue by michaeloverton** [Ayfel/PrefabLightmapping#41]
Thank you so much for your work on this. This is really great stuff. I am having an issue with the lightmaps sometimes not being applied to my prefabs (happens about 30% of the time).

I am trying to build an "infinite office space". I make prefab rooms, and then as the player traverses the rooms, more are generated on the fly, and old ones are destroyed. To generate the lightmaps, I have put each room in its own scene, and I then use your "Bake Prefab Lightmaps" option. This works, and populates the Prefab Lightmap Data on each prefab room. Within each room's scene, I can also drag in copies of that room, and the lighting works on each one.

For the actual "game", I `Instantiate()` the prefabs using a script. Most of the time, the lighting is correct, but sometimes, the lighting looks very strange. Do you have any ideas why this would be happening?

Here are some relevant images:
https://imgur.com/a/KBlkGAb

When I baked the lighting, I set everything in the prefab as Static. After baking, I tried making the prefabs NOT static. This did not fix the problem. I also tried keeping them static and had the same problem.

The inconsistency is very confusing to me. Any help would be amazing. Thank you so so much.

**Comment by michaeloverton** [comment]
note: in the images, i made a typo - below the third image, it should say `dragging PREFABS into scene gives correct lighting`

**Comment by Ayfel** [comment]
Can you share your lighting settings, what type of lights you use (mixed, baked, realtime, etc) and how this lighting is setup? Also what render pipeline you use.

**Comment by Ayfel** [comment]
Also you said sometimes the lighting is wrong but sometimes is fine, does it happen consistently with the same prefabs that the lighting is not working? Do you get the same result in a build vs the editor?

**Comment by michaeloverton** [comment]
Thanks for your response.

1. The lighting issues happen with all prefabs. It does NOT happen with just some prefabs.
2. I get the same results in the editor and both production and development builds.
3. In an attempt to fix the problem, I made ALL lights be baked. They are mostly baked point lights and some baked area lights. One weirdness I noticed is that sometimes even if I delete the prefab lighting data, and even though the point lights are set to "baked", I end up seeing light in the prefab (in this case, shouldn't the prefab be dark, because I have baked no light?)
4. I'm using the standard render pipeline.

Could this be a side effect of the materials that are being used on the assets? I noticed on some assets, the material being used has Emission Global Illumination set to Realtime. Would this make a difference?

Another thing I notice is that the walls of my prefab rooms are actually 3D Planes (as opposed to solid boxes). Could this cause problems?

It is confusing to me because in the case where the lighting is bad, the lightmap is actually still applied, but the lightmap appears to be darkened. I know the lightmap is applied, because if it weren't the asset would simply be nearly black, right?

Here are some relevant images and descriptions.

https://imgur.com/a/ZC4JKAC

Thank you so much for your help. I'm not a lighting expert - I am learning about this stuff as I go.

**Comment by michaeloverton** [comment]
Also, I am using Unity 2019.4.13f1 if that helps...

**Comment by Ayfel** [comment]
It shouldn't be because of materials at all. It also looks like the prefab has lightmaps applied as all the shadows show there in the same way. An easy way to see this is to disable all lights in the scene and see if they have still light/shadows. It feels like there is some extra light when it looks fine that's why I was asking. Is there a way you could make a reproducible project for me to check or similar. I am not seeing anything obvious wrong here and the setup is basically the same I mostly use, Unity 2019 and Standard render pipeline with regular lighting settings. I recommend setting the Bake Lighting Mode to "Bake Indirect" instead though so it will bake everything. Let me know after you test that.

**Comment by zcwaa22** [comment]
Hi @Ayfel and @michaeloverton Sorry to hijack this thread but I thought I'd share what I've found in relation to this issue.

I'm also creating a "infinite" space, a corridor that is instantiated as you move along it. My root "block" prefabs contain, walls and door and its these "block" prefabs which I first add the PrefabLighmapData script to, bake and then instantiate at runtime.

What I've been finding is that instantiated "blocks" which have a rotation of 0 on the Y axis look perfect but as soon as I instantiate them at 90, 180 or 270, or indeed change the transform's value of Y rotation while the engine is running the lightmaps get dark and blotchy.

 I'm new to lighting so maybe this is an error on my part elsewhere but if not it might help shed some light on what's happening?

**Comment by michaeloverton** [comment]
@zcwaa22 Oh, excellent observation! I haven't tested that. Does it happen when you manually place the prefabs into a new scene (by hand as opposed to script instantiation) and rotate them? Any ideas about this @Ayfel ?

**Comment by zcwaa22** [comment]
> @zcwaa22 Oh, excellent observation! I haven't tested that. Does it happen when you manually place the prefabs into a new scene (by hand as opposed to script instantiation) and rotate them? Any ideas about this @Ayfel ? I will test this on my end soon.

Yep. Both dragging a baked lightmapped prefab and rotating it when the scene isn't running and when the scene is running produces the same undesired result for me..

**Comment by Ayfel** [comment]
Oh so its the Directional mode that was causing it for you? I'll need to test that out

**Comment by michaeloverton** [comment]
I've confirmed that this is indeed the case for me as well. The issue is the worst when the rotation is 180 degrees, but it is also incorrect at 90 and 270.

This does make me think of a potential workaround, though - make separate prefabs with separate lightmaps for each rotation, and swap them in as necessary. This would really not be ideal, however...

Here is an example: https://imgur.com/a/hIJfNJp

**Comment by zcwaa22** [comment]
Hi @michaeloverton have you tried changing the directional mode in lightmapper settings- this is what fixed the issue for me

**Comment by michaeloverton** [comment]
That fixed it for me too! Thank you so much. So if I'm understanding things correctly, this is because: 

```
When you bake a Directional lightmap, Unity generates two lightmap textures. One texture stores information about the intensity and color of the lighting received across the target surface. This is identical to the Non-Directional lightmap. The other texture stores the dominant light direction, along with a factor describing how much of the total light received comes from that dominant direction.
```

The "second texture" about the dominant light direction is what makes the lightmap incorrect upon rotation in our case. Makes sense.

Thank you so much, both of you. Will close the issue.

**Comment by michaeloverton** [comment]
@Ayfel thanks again. It might be a good idea to put something in the FAQ about not using directional lightmaps if the prefabs will be rotated. Up to you, though, as I know you're probably busy.

**Comment by Ayfel** [comment]
Yes I agree, I want to explore the reason behind this because initially I had disabled directional lightmapping and defaulting everything to non-directional and later on re-enabled the option because everything seemed to work fine. I want to understand how Unity store this directional information.
