### ISSUE TITLE
Does not cooperate with Postprocessing and Aura 2

### ISSUE THREAD

**Issue by rakkar1974** [Ayfel/PrefabLightmapping#5]
Perhaps this is outside the scope of this project, but the results are significantly different between the editor scene, and the lightmapped prefab in another scene with an otherwise identical setup. The scene on the right is from the scene view during play mode, but the game view is equivalent.

Postprocessing is darker than it should be, lights are not taken into account somehow
Aura 2 light isn't working, producing strong spotlight halo effects.

Unfortunately, due to the size and complexity of my project I can't easily give you a repro case.

Post Processing from the Package Manager, version 2.1.7
Aura 2, version 2.1
https://assetstore.unity.com/detail/tools/particles-effects/aura-2-volumetric-lighting-fog-137148

![SceneVsRuntimeResults](https://user-images.githubusercontent.com/32167612/69341218-22838280-0c37-11ea-8a12-6b2d4d8651a1.png)

**Comment by Ayfel** [comment]
Thanks for the pics, I had not tried aura 2 indeed so I am not sure even how they actually work and it would take me a while. If you make a simple repo project with two basic scenes with a similar setup I will be happy to check it out to understand it (no need for your actual project, just something basic).

**Comment by rakkar1974** [comment]
Thanks for the quick reply. This isn't high priority for me so I'll stick using my current workflow using Bakery, which also supports prefabs with baked lightmaps and works correctly with Aura 2 and post processing. If you want to investigate this in the future it may help others.

**Comment by Ayfel** [comment]
Ok thanks, definitely will keep it in mind if more people ask of it : )
