### ISSUE TITLE
Clarification of Light Probes

### ISSUE THREAD

**Issue by FalseP** [Ayfel/PrefabLightmapping#50]
This stuff is a godsend for procedural devs but I would like some clarification on the light probes.

When you say "create a uniform light probe group in the scene you are going to instantiate prefabs at" do the light probe groups really have to be perfectly uniform? 

Also, since they have to already be in the scene itself, and not within the prefabs, how would we fine tune where they end up once the prefabs instantiate (i.e. preventing them from being in walls, getting them to be in crucial areas where the light changes substantially)?

**Comment by Ayfel** [comment]
Yes, clearly thats a limitation, you can do  more complicated setups (and it depends in the procedural setup and spatial configurations you use) but where I have gotten good results has been with those uniformly spaced configurations, even when a probe fell somewhere I didnt want it, in general it wasn't a big issue. You will not get perfect, but all the use cases I have seen have been pretty good overall.

**Comment by FalseP** [comment]
Ok, thank you very much for the clarification. So to confirm: the only mandatory requirement is that the light probes must be in a scene and then have an empty bake done, with uniform groups giving the bets results?

If the above is true have you thought of adding an option to have the probes placed in the prefabs instead? I'm very surprised unity has nothing like this and think that this should have much more attention.

**Comment by Ayfel** [comment]
It is a known issue and the calculation that is done at bake time is not available at runtime so thats the reason the light probes won't help being inside a prefab.

And yes only requirement is probes and empty bake.

**Comment by Ayfel** [comment]
Some literature woth looking at https://forum.unity.com/threads/any-runtime-dynamic-baking-options-or-are-any-coming.821676/#post-5612233
