### ISSUE TITLE
Baking lightning on a prefab overwrite other prefabs lightmaps

### ISSUE THREAD

**Issue by EmptyBottleInc** [Ayfel/PrefabLightmapping#52]
Hi I don't really know if I'm trying to do something the script is not supposed to, or if I'm missing something.

I used this script to bake lightmaps on a level of my project which is loaded at runtime, and I didn't got any issues. But, once I bake another level, the lightmaps of all the previous are overwritten. I think it's because I use the same scene to bake all the levels, but if so, should I create a scene for every levels I need ?

**Comment by Ayfel** [comment]
Yes, that's the issue, since the lightmaps are "linked" to a scene, another thing you can do is bake and then move those lightmaps somewhere else in your project, because the new bakes will only override them in that specific folder where they get created

**Comment by EmptyBottleInc** [comment]
It works, I can actually move the lightmaps in another folder, I didn't think in that way. Thank you for your quick help.

**Comment by emrguzel** [comment]
> Yes, that's the issue, since the lightmaps are "linked" to a scene, another thing you can do is bake and then move those lightmaps somewhere else in your project, because the new bakes will only override them in that specific folder where they get created

Seems to be not working for Unity 6000.0.33f1, old lightmap files are being deleted, then replaced with new ones in the default directory.
