### ISSUE TITLE
Transparency in Build

### ISSUE THREAD

**Issue by Baltzs** [Ayfel/PrefabLightmapping#64]
**Hello there,**

_First of all, your addon is a really helpfull and powerfull feature that should be in unity by default, so thank you very much for your work._

I'm writing to you as I don't think this issue has been mentionned before.

I'm working with **Unity 2021.3.23, on HDRP.**

Our game is a **rogue like** where each room is being instanciated in a **specific scene as a prefab**.

In theses rooms, specific walls are made of a single **mesh with multiple materials**, for the walls and windows. (2 opaque 1 transparent for the window).
When baking theses, **in the editor everything works fine**, window's transparency is being correctly displayed.
However **_when building the project, every single object that was baked looses it's transparency_**, (I think decals are also affected by this). 

**I've solved this issued by not baking any transparent materials**, however that would mean **we would have to split all of our transparent meshes**.

 Is this somehting that we absolutely have to do, or is it possible to have the build working like in the editor?

I don't fully understand how the lightmaps are read in the build, and might be missing something, and I hoped you could enlight me about a thing or two.

Hope you find the time to help us out! Thanks again!

![image_2023-12-11_114202197](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/b3288a63-8707-44b5-8ba3-31c6c1547b91)

**Comment by Ayfel** [comment]
Hi,

If you bake a regular transparent object and build a scene with that object (without instantiation, to rule out the prefab light mapping) does it work properly? I am not sure why this would be happening so let's dig a bit on how things are setup. Are you loading your prefabs from disk, from assetbundles?

**Comment by Ayfel** [comment]
Can you take a look at your graphics settings in project settings, it might look different in HDRP but you should take a look at shader stripping etc to make sure all modes you need are included 

![image](https://github.com/Ayfel/PrefabLightmapping/assets/13970424/9c54d92d-2af0-4f5e-80dc-763b08b70054)

**Comment by Baltzs** [comment]
Yes, sorry i should have mentionned i did the thing you suggested on other posts before submitting.

Here is it under HDRP, does it looks okay to you? 


![image](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/643e0934-6d03-458e-8791-231eff4e00d8)

**Comment by Ayfel** [comment]
Thanks, can you change the instancing variants to not strip?

![image](https://github.com/Ayfel/PrefabLightmapping/assets/13970424/3207a8d0-4864-4e56-add6-e7f83fb74113)

**Comment by Baltzs** [comment]
I set it up to "keep all", built the same scene again, stil did not work, but it did took some time to build (~20 min).

![image](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/97ea1396-2200-4592-aa8d-560e1ffb0f9f)

![image](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/10bdf061-811b-4419-bcb9-20059b2b7f23)

**Comment by Ayfel** [comment]
can you make a small repo project for me to check? just same version of unity, hdrp and settings with a simple model/material and prefab for me to check. I suspect something in the HDRP shaders is making it do this, but its probably version specific too

**Comment by Baltzs** [comment]
Okay, sorry for the delay.

I've created a specific repo based on our main one, I've sent you an invitation.

I've set up three windows: one which has a prefab lightmap, another one that shares the same material as the prefab but is not a prefab, and a last one which has its own material and not a prefab.

The prefab lightmap is opaque again, and the interesting thing is that the material on the other window that is not supposed to have the lightmap prefab is also opaque.

**_This means that if a mesh shares the same transparent material as a prefab lightmap, it also loses its transparency_**

Hope you can check that and understand something about it! Thanks again!

![image](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/541324db-6742-44fd-9154-a65284475f6e)

**Comment by Ayfel** [comment]
So when the system applies the lightmaps it reassigns shaders, as this was needed in certain cases and certain materials. For this HDRP shaders it seems like that is causing the "transparent" keyword to be lost. So I added a new bool to the script, you can uncheck this in your prefabs and it seems to work well. 

![image](https://github.com/Ayfel/PrefabLightmapping/assets/13970424/7bba3aad-4baf-4cb5-934d-98c52d90f008)

![image](https://github.com/Ayfel/PrefabLightmapping/assets/13970424/f2aa0704-65d6-43d1-9294-084f248fe25c)

Download the latest version from master to access that. I left it true by default but you can uncheck it.

**Comment by Baltzs** [comment]
Thank you so much for your quick answer and reaction!!

Just made another build and it works perfectly! This is awsome and a great load off of our shoulders!

Hope you have a wonderfull day, thanks again !! 

![image](https://github.com/Ayfel/PrefabLightmapping/assets/130995235/1e0ab3af-8eee-4c66-9802-b6f36dc11261)

**Comment by Ayfel** [comment]
Happy to help : )

**Comment by Nattuhan** [comment]
@Ayfel 
Hi, thank you for the great source code.
I faced the same problem and came across this issue and solution.
If possible, I would like to know what the purpose of the few lines of processing that are skipped when the bool is set to false are originally written for ("release shaders" are needed in specific cases, for optimization, etc...). ).
Thanks.

**Comment by Ayfel** [comment]
So that line just reassigns the shaders to the materials, and it is (was) necessary in certain cases where the lightmap wouldn't show up unless the shader was reassigned/reset. I have found that different versions of Unity behave differently in some cases and this is a regression that happens in some cases when loading from assetbundles etc. Technically it shouldn't be necessary but sometimes it is unfortunately.
