### ISSUE TITLE
Trying to set shader on a Material Variant

### ISSUE THREAD

**Issue by BraveShundesign** [Ayfel/PrefabLightmapping#65]
I am using Unity 2022.3.14 URP rendering pipeline. There is no problem when running in the editor, but when I build, I get an error, Trying to set shader on a Material Variant., how should I solve it? Thanks

**Comment by BraveShundesign** [comment]
![Snipaste_2024-02-01_01-21-08](https://github.com/Ayfel/PrefabLightmapping/assets/57254247/db49e3c3-b32a-4535-9f53-473164df80f8)

**Comment by Ayfel** [comment]
There is a new bool in the script called "releaseShaders". Try to unselect it, that should fix that issue I believe.

**Comment by BraveShundesign** [comment]
> 脚本中有一个名为“releaseShaders”的新布尔值。尝试取消选择它，我相信这应该可以解决该问题。

Thank you so much for solving my problem, what a great resource otherwise my project wouldn't work, thanks again
