### ISSUE TITLE
Lightmaps Too Bright on Android Bundle

### ISSUE THREAD

**Issue by art3miz18** [Ayfel/PrefabLightmapping#66]
Hello, I have been using these scripts to create preffabed Lightmaps that could then be used in conjunction with Asset Bundle, i am building the same for 3 platforms (Android Web and Editor/Desktop) it works fine in both apart from Android. 
the asset Bundle is loaded with Exposed lighting in the scene when built and run on android

**Comment by Ayfel** [comment]
Try switching in the editor to Android in your build settings and make sure the prefabs look fine there in the editor. Sometimes when baking lighting from Windows or some other platform, your android one might look different. As a reference I use the same method with asset bundles for all platforms (Android, Mac, IOS, Windows, Web) with no issue so I would suspect is something else.

**Comment by art3miz18** [comment]
marking issue as closed, It did fix the issue
the main problem was between the lightmap format once the baking was done. i ended up using automatic compressed RGB 32 bit 
and yeah of course changing the build platform to Android while building the lightmaps fixed these issues 

thanks again @Ayfel
