### ISSUE TITLE
How to merge LightingData assets for correct shading working?

### ISSUE THREAD

**Issue by dimbodek** [Ayfel/PrefabLightmapping#69]
Hi, i use one scene for bake many prefabs separete because they do not depent from each other, so for saving time i bake each separete in same scene. So after each bake Lightmapper generate LightingData for last bake, and i've seen that without this date other prefabs not showing correct.

**Comment by Ayfel** [comment]
You can simply move your lightmapped textures after each bake, they don't need to be in the default folder unity puts them (which is why you are losing them I think), and that is all you need to be able to light your prefabs. So baking and moving the textures should be good for your usecase.

**Comment by dimbodek** [comment]
Beside textures unity also generates lightmapping data asset which some how also involve on shading visual and only one such asset can be applied to scene, so this is reason why i can bake separete prefabs.

**Comment by dimbodek** [comment]
Bakary do not generate such asset, i think it's just different lightning models, but unity does after each bake and such asset can be applied only to scene

**Comment by Ayfel** [comment]
The lightmap data asset is not used by this code at all, its only used by Unity "while" baking and in the settings. This script only references the lightmap textures when instantiating, etc. So simply moving them in your assets like I mentioned before should fix your issues.

**Comment by dimbodek** [comment]
unity uses lightmap data asset in play mode too

**Comment by Ayfel** [comment]
This script (PrefabLightmapData.cs) doesn't, so I am not sure what your point is. I am going to close the thread as clearly there is not a bug or an issue and we are just discussing a point that is not relevant to the functionality of the code in this repo.

**Comment by dimbodek** [comment]
![1](https://github.com/Ayfel/PrefabLightmapping/assets/87578779/e91d4af2-a364-4289-9788-5fab16c172df)
![2](https://github.com/Ayfel/PrefabLightmapping/assets/87578779/1e3c18af-74f3-4e66-9d7c-46d7e4274ecf)
with assets and without, is shoud this plugin handle this in some way?

**Comment by Ayfel** [comment]
That looks like a real time light affecting the prefab or the scene environment lighting, etc.

**Comment by dimbodek** [comment]
yep, you are right, when remove this asset unity starts applyed mixed subtractive light(which i used for bake) like realtime directional

**Comment by dimbodek** [comment]
it's little bit distracted that when u use baked prefabs in another scene, unity applies mixed subtractive lights to them
