### ISSUE TITLE
Lightmap changes when scene is changed.

### ISSUE THREAD

**Issue by ituitis-cimena19** [Ayfel/PrefabLightmapping#7]
Hello, im a beginner trying to make a procedural driving game. My road is being made at runtime so i needed your script for saving my lightning data. So i did;
1)Put my road prefabs on a scene with a baked light(streetlamp)
2)Baked prefab lightmaps from Assets/Bake Prefab Lightmaps
3)Built the game on android platform, with Baking scene first, playing scene second.
When i run the game on play mode, everything is fine. My baked data transfers to the second scene and there is no problem. But on android build it breaks.

This is the first scene where i baked the data, the normal lightmap should be like this so it is baked fine. When the button is pressed, i proceed to the second scene where the game is played.
![](https://user-images.githubusercontent.com/56236795/72163545-1022fb00-33d5-11ea-9c61-08f4b2cf7e31.jpeg)

And this is the second scene where the magic happens. The textures are partly black, partly lit.
![](https://user-images.githubusercontent.com/56236795/72163544-1022fb00-33d5-11ea-8d2d-b6c7d061235e.jpeg)

I have post processing on the playing scene so i thought maybe it is the reason, but when i deactivated it nothing changes, still black textures. Been trying to fix this for almost a week. Any help would be amazing, thanks.

**Comment by Ayfel** [comment]
Check the repo readme in case the issue is that no shaders are being included in the build due to shader stripping. That's most likely the case from what I gather

**Comment by ituitis-cimena19** [comment]
I have tried it, on automatic, custom (tried import from this scene and tried other varieties) and nothing changed, not even a bit.

**Comment by Ayfel** [comment]
Can you send me a repo case? Basically a scene with it so I can test it. Also what version of Unity are you on?

**Comment by ituitis-cimena19** [comment]
Really sorry for the late answer, after you asked for a case, i decided to make a mini project to send, then i found the solution which is irrelevant to your code. It works like a charm, thanks
