### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by drallcom3** [Ayfel/PrefabLightmapping#8]
1. Create new project: 2019 + Uwrp (Old 3D has the same issue)
2. Create scene, set to subtractive lighting.
3. Create plane+cube, add script, make prefab out of them.
4. Bake lightmap, bake prefab from menu.
5. Create new scene, put prefab in it.
6. Hit play.
The lightmaps on the prefabs kind of get loaded, but they have heavy black/white/pink artifacts. The whole prefab is also affected by realtime lighting.
Does it not work or am I doing something wrong?

![lightmap](https://user-images.githubusercontent.com/25057147/74781790-1a6cca80-529a-11ea-8d50-89a0d5ea1f66.png)

**Comment by Ayfel** [comment]
Uncheck static in the new scene, I am out for a week, if you still have issues i Will check Next week, thanks

**Comment by drallcom3** [comment]
Fix: I have to create the lightmap with **Directional** enabled. Now it seems to work (static or not doesn't matter).
Would be nice if non-directional would work, too. I don't think mobile games ever use directional.

**Comment by Ayfel** [comment]
Oh yes i have that fixed and included, I will push it when I am back

**Comment by drallcom3** [comment]
Looking forward to it. I can wait a week.
